### ISSUE TITLE
Add support for Github enterprise

### ISSUE THREAD

**Issue by noamd-legit** [Legit-Labs/legitify#10]
### TL;DR

Support scanning GHES for misconfigurations

**Comment by carltonmason** [comment]
Glad I looked as I was going to open an issue requesting support for GitHub Enterprise.

This is what I get when I try against our IBM GHE:

```console
 go run main.go analyze --org https://github.ibm.com/CICD-CPP-Ops --namespace repository
 ___      _______  _______  ___   _______  ___   _______  __   __
|   |    |       ||       ||   | |       ||   | |       ||  | |  |
|   |    |    ___||    ___||   | |_     _||   | |    ___||  |_|  |
|   |    |   |___ |   | __ |   |   |   |  |   | |   |___ |       |
|   |___ |    ___||   ||  ||   |   |   |  |   | |    ___||_     _|
|       ||   |___ |   |_| ||   |   |   |  |   | |   |      |   |
|_______||_______||_______||___|   |___|  |___| |___|      |___|
By Legit Security

Error: GitHub token seems invalid (should start with "ghp_"
2022/11/10 14:03:19 error executing command: GitHub token seems invalid (should start with "ghp_"
exit status 1
```

Thanks

**Comment by noamd-legit** [comment]
Hey @carltonmason
What kind of GitHub token are you using?

**Comment by carltonmason** [comment]
A GHE personal access token.

**Comment by gal-legit** [comment]
@carltonmason is that a fine-grained token?
If this is a classic token that doesn't have the `ghp_` prefix, then we can remove this check for GHES (which was just merged https://github.com/Legit-Labs/legitify/pull/40)

**Comment by carltonmason** [comment]
I am not sure if its a fine-grain token or how to tell if it is.  I have several GHE tokens and think the one I am using is:
![image](https://user-images.githubusercontent.com/14194291/201371270-2dc16d03-d283-4988-97a3-97fbe0d7da56.png)

**Comment by gal-legit** [comment]
@carltonmason looks like your token is a classic one.
I'm gonna open a separate issue to remove the prefix limitation for GHES
