### ISSUE TITLE
GitHub Actions - Support output format compatible with Job Summaries

### ISSUE THREAD

**Issue by dimapasko** [Legit-Labs/legitify#105]
### TL;DR

With the release of version 0.2.0, you officially added support for GitHub Actions to Legitify. 

I've been experimenting with the examples at https://github.com/Legit-Labs/legitify/tree/main/action_examples and I think it would be beneficial for our use case to also have support for [GitHub Actions Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). 

Thanks for creating such a promising product!

### Detailed design

```markdown
Add yet another `--output-format` to the `legitify analyze`

Possible names `job-summary` or `markdown`
```

**Comment by gofri** [comment]
I really love this idea! Thank you for this suggestion!
I don't think it'd be too much trouble to implement it.
While at it, we might want to support multiple output formats for the same run (the only problem is finding a simple way to specify in the CLI which fotmat goes to which file)

**Comment by noamd-legit** [comment]
Closing this issue.
@dimapasko Appreciate it if you could provide some feedback on the Job Summaries support 😄

**Comment by dimapasko** [comment]
It works, thanks! 🚀

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/48351/212648135-0f298e7f-81f5-4310-9106-f53924ad93e0.png">

It would be beneficial to include "Legitify" in the summary, as there is another task with a similar title in our case. 

Thank you for the fast solution and for the exceptional product. I will provide further feedback as we continue to utilize it further.

**Comment by gal-legit** [comment]
@dimapasko 
https://github.com/Legit-Labs/legitify/pull/116
:)
