### ISSUE TITLE
Support SARIF output format

### ISSUE THREAD

**Issue by noamd-legit** [Legit-Labs/legitify#11]
### TL;DR

Add SARIF as an additional output format

**Comment by gal-legit** [comment]
adding a reference to GitHub's SARIF for code-scanning:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning

**Comment by chtzvt** [comment]
Hey folks!

Just so you know, I'm nearly finished implementing this feature. Expect a PR soon 😃
