### ISSUE TITLE
Incorrect link in the README

### ISSUE THREAD

**Issue by rajbos** [Legit-Labs/legitify#111]
### TL;DR

The link [here ](https://github.com/Legit-Labs/legitify/blob/main/README.md#policies)does not work correctly: 

Goes to `https://legitify.dev/policies.html`.

### Expected behavior

Links should work 😉 

### Observed behavior

Error

### Version

README

### On which operating system are you using legitify?

Other (please elaborate in the description)

### Relevant log output

```text
GitHub UI
```

**Comment by noamd-legit** [comment]
Indeed links should work :) Thanks!

**Comment by rajbos** [comment]
Thanks for fixing that!
