### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by gal-legit** [Legit-Labs/legitify#12]
### TL;DR

Prepare a GitHub action for easy integration of legitify as a periodic scanner to keep organizations/repositories secure.

### Detailed design

```markdown
This could be implemented as:
1. Workflow template
2. Preferably - An action that wraps legitify and runs it with the relevant parameters.
```

**Comment by peckjon** [comment]
+1 to this ... would make it much easier to utilize as part of standard checks. Tagged properly, would show up in https://github.com/marketplace?category=security&type=actions

**Comment by gal-legit** [comment]
Preferably use slsa-verifier to verify the binary in the action (pending #36)

**Comment by noamd-legit** [comment]
Closing this issue. @shay-legit Added legitify action in v0.2.0 🔥 
@peckjon Appreciate it if you have any feedback

**Comment by peckjon** [comment]
Awesome @shay-legit ! The example YML looks great but I’m unable to find this Action in the [Actions Marketplace](https://github.com/marketplace?type=actions)— do you have a direct link or is it still in review?

**Comment by noamd-legit** [comment]
https://github.com/marketplace/actions/legitify-analyze
Just added 😄
