### ISSUE TITLE
Ability to pass arguments to the GitHub action

### ISSUE THREAD

**Issue by raoganeshr** [Legit-Labs/legitify#124]
### TL;DR

I dont see a way to pass arguments to the legitify executable when we use the GitHub Action. Can that be enabled? e.g. --scorecard

**Comment by noamd-legit** [comment]
@raoganeshr 
Thanks for the feedback. I added scorecard support in the action. Unfortunately it might worsen your rate limit problems.. could you check it out? 
Closing the issues in the meanwhile.

**Comment by raoganeshr** [comment]
Thank @noamd-legit . I moved away from the action to directly download and run legitify to allow me more flexibility. To reduce the rate limiting issue, I have split my workflows to run scans on repos and other namespaces in separate workflows on different schedules. Thanks for your prompt response.
