### ISSUE TITLE
By default only 50 repositories are analyzed

### ISSUE THREAD

**Issue by raoganeshr** [Legit-Labs/legitify#126]
### TL;DR

I used the GitHub action and it only reported issues for 50 repos.

### Expected behavior

I expected a report for all the 100+ repositories in the organization.

### Version

0.2.0

### On which operating system are you using legitify?

Linux

**Comment by noamd-legit** [comment]
Hey @raoganeshr, could you provide more information or attach the build log & error log (if they dont contain sensitive information)

**Comment by raoganeshr** [comment]
I lost that action run. Will close the case for now.
