### ISSUE TITLE
Make clean does not clean docs

### ISSUE THREAD

**Issue by derekmurawsky** [Legit-Labs/legitify#142]
### TL;DR

When you `make clean` it only cleans the built binary. It does not clean the autogenerated docs directories. 
Further, the generated docs are not in the `.gitignore` file. 
This is a bad combo. Ask my how I know... 🤣 

### Expected behavior

Make clean should clean anything that is generated by other make commands. 
The .gitignore should include the transient items that are generated via other make commands, like generated docs. 

### Version

latest

### On which operating system are you using legitify?

Mac OS

**Comment by noamd-legit** [comment]
Closing the issue as @morelmiles fixed it.
