### ISSUE TITLE
Homebrew installation

### ISSUE THREAD

**Issue by eriweb** [Legit-Labs/legitify#163]
### TL;DR

Would you consider adding support for installation by Homebrew? 
goreleaser has built in support for creating taps

**Comment by noamd-legit** [comment]
@eriweb great idea. @nadav-legit is working on it

**Comment by nadav-legit** [comment]
Hi @eriweb thanks for the idea.
We've added support for brew, currently only for x86 macos.
We weren't able to use goreleaser brew extension because we're singing macos binaries which cannot be combined with the rest of our release workflow and brew.
