### ISSUE TITLE
Rate Limit 

### ISSUE THREAD

**Issue by fatihgrel** [Legit-Labs/legitify#188]
### TL;DR

When Legitify was run, after scanning some of the repositories, it waited for the rate limit for 60 seconds. But it returned the result without continuing to scan the remaining repositories

### Expected behavior

I was expecting all repository to be scanned.

### Version

0.2.5

### On which operating system are you using legitify?

Mac OS

**Comment by gal-legit** [comment]
hey @fatihgrel, could you please provide more info and the relevant log output?
secondary rate limits should not have any effect on the scan result

**Comment by fatihgrel** [comment]
The number of repositories scanned changes when I run it more than once. However, not all 848 repositories are screened in any scan.

<img width="742" alt="Screenshot 2023-04-24 at 13 23 01" src="https://user-images.githubusercontent.com/112947076/235661549-cefff7bd-1261-45f4-94b4-03561174b09d.png">

**Comment by gal-legit** [comment]
@fatihgrel 
I see the `panic: send on closed channel`, which suggests there's a bug here.
could you please share the error log for the investgiation?

**Comment by fatihgrel** [comment]
failed to collect webhooks data for my_company_name_redacted, GET https://XXXXXXX: 404 Not Found []
facing secondary rate limit with request: https://XXXXXXX sleeping until: 2023-05-09 17:58:13.87168 +0300 +03 m=+74.604681085
facing secondary rate limit with request: https://XXXXXXX sleeping until: 2023-05-09 17:59:25.390912 +0300 +03 m=+146.123306335
error getting repository dependency manifests for my_company_name_redacted/XXXXXXX: timedout
error getting repository dependency manifests for my_company_name_redacted/XXXXXXX: timedout
error getting repository dependency manifests for my_company_name_redacted/XXXXXXX: timedout
facing secondary rate limit with request: https://XXXXXXX. sleeping until: 2023-05-09 18:00:34.472384 +0300 +03 m=+215.204187876
error getting repository dependency manifests for my_company_name_redacted/XXXXXXX: timedout
error getting repository dependency manifests for my_company_name_redacted/XXXXXXX: timedout
facing secondary rate limit with request: https://XXXXXXX sleeping until:

**Missing permissions errors:
missing permission: "read:org" on:
    - organization:my_company_name_redacted [Some information cannot be collected because the organization is not part of an enterprise]
missing permission: "admin:org_hook" on:
    - organization:my_company_name_redacted [Cannot read organization webhooks]
missing permission: "XXXXXXX" on:
    - repository:my_company_name_redacted/XXXXXXX [Branch protection cannot be collected because the organization is in free plan]**
    .
    .
    .

Unmet Prerequisites errors
Skipping policy: default_repository_permission_is_not_none, missing scope: read:enterprise
Skipping policy: stale_admin_found, missing prerequisite: premium
Skipping policy: stale_member_found, missing prerequisite: premium
Skipping policy: scorecard_score_too_low, missing prerequisite: scorecard_enabled
.
.
.

I know that the error I wrote in bold is due to our github profile. I put that part in order not to miss out. But I have no idea about the others. The organization was run with the admin token.

**Comment by gal-legit** [comment]
@fatihgrel - thanks for the info. we'll try to reproduce locally and fix.
If we fail to reproduce it, we'd be glad to communicate privately to get to the bottom of this issue and fix legitify to work for you.
please feel free to reach out @ gal@legitsecurity.com

**Comment by gal-legit** [comment]
@fatihgrel 
I failed to reproduce the bug locally.
I suspect it might be related to #175, so would be great if you could retry with v0.2.6 (or main).

**Comment by fatihgrel** [comment]
Hi again,

failed to collect webhooks data for useinsider, GET https://XXXXXXX: 404 Not Found []
error getting repository dependency manifests for useinsider/gachapon: timedout
error getting repository dependency manifests for useinsider/pandora-config-generator: timedout
facing secondary rate limit with request: https://XXXXXXX. sleeping until: 2023-05-16 14:06:06.917613 +0300 +03 m=+72.619974960
error getting repository dependency manifests for useinsider/expo-test-app: timedout
error getting repository dependency manifests for useinsider/atlas: timedout
facing secondary rate limit with request: https://XXXXXXX sleeping until: 2023-05-16 14:07:20.569327 +0300 +03 m=+146.271406251
facing secondary rate limit with request: https://XXXXXXX sleeping until: 2023-05-16 14:08:31.630063 +0300 +03 m=+217.331869668

**Missing permissions errors:
missing permission: "read:org" on:
    - organization:my_company_name_redacted [Some information cannot be collected because the organization is not part of an enterprise]
missing permission: "admin:org_hook" on:
    - organization:my_company_name_redacted [Cannot read organization webhooks]
missing permission: "repo" on:
    - repository:my_company_name_redacted/XXXXXXXX [Branch protection cannot be collected because the organization is in free plan]
    - repository:my_company_name_redacted/XXXXXXXX [Branch protection cannot be collected because the organization is in free plan]
    .
    .
    .**

Unmet Prerequisites errors
Skipping policy: default_repository_permission_is_not_none, missing scope: read:enterprise
Skipping policy: stale_member_found, missing prerequisite: premium
Skipping policy: stale_admin_found, missing prerequisite: premium
Skipping policy: scorecard_score_too_low, missing prerequisite: scorecard_enabled
Skipping policy: scorecard_score_too_low, missing prerequisite: scorecard_enabled
.
.
.

I know that the error I wrote in bold is due to our github profile. I put that part so you don't miss it. The installation was run with the admin token and the latest version was used. I'll be happy if you can help me. Thank you for your efforts.

**Comment by gal-legit** [comment]
Hey @fatihgrel.
We analyzed the logs you provided, but we fail to detect or reproduce the bug.
Just to be clear, we don't think that the issue originates in the rate limits.

In order to understand the issue, we need to have the full log from legitify (redacted).
In addition, could you provide the cmdline used to run legitify?
If special env vars are used (e.g. SERVER_URL), please mention them too (redacted).

thanks

**Comment by gal-legit** [comment]
hey @fatihgrel,
we added a few fixes to permissions and rate limits that should improve the stability.
please reopen the issue if the problem persists.
