### ISSUE TITLE
Wrong detection by "organization_has_too_many_admins" check

### ISSUE THREAD

**Issue by marksarka** [Legit-Labs/legitify#204]
### TL;DR

We have 2 admin users in our GitHub organization but legitify alerts on that as if we have too many admins.

### Expected behavior

I would expect that 3 admins and above will be considered too many.

### Version

0.2.6

### On which operating system are you using legitify?

Mac OS

**Comment by royb-legit** [comment]
Hi @marksarka, thanks for raising this issue!
It's fixed in [v0.2.7](https://github.com/Legit-Labs/legitify/releases/tag/v0.2.7), please reopen this issue if you see otherwise.
