### ISSUE TITLE
Support GitHub Org level branch policies

### ISSUE THREAD

**Issue by raoganeshr** [Legit-Labs/legitify#209]
### TL;DR

GitHub is now supporting org level branch policies. This means that we no longer need to define it at repo levels.

### Detailed design

```markdown
With org level branch policies, the actual branch policies will be a combination of the stricter policy at org and repo. Legitify should take both into consideration for the compliance run.
```

**Comment by royb-legit** [comment]
Hi @raoganeshr, thanks for opening this issue!
Just to make sure, are you referring to the new "Rulesets" which is currently in beta?

**Comment by noamd-legit** [comment]
I've added support for rulesets [here](https://github.com/Legit-Labs/legitify/pull/221)

**Comment by raoganeshr** [comment]
> Hi @raoganeshr, thanks for opening this issue! Just to make sure, are you referring to the new "Rulesets" which is currently in beta?

Yes Roy.
