### ISSUE TITLE
When running on an org in which I'm not an owner, there's a false-positive result

### ISSUE THREAD

**Issue by royb-legit** [Legit-Labs/legitify#22]
### TL;DR

Running `analyze --org some_org` shows all results as skipped, except for one policy "Non-Admins Can Create Public Repositories" which shows as failed, even though I'm not an owner on some_org.

### Expected behavior

In the results, show "Non-Admins Can Create Public Repositories" as skipped

### Observed behavior

In the results, "Non-Admins Can Create Public Repositories" appears as failed

### Version

0.1

### On which operating system are you using legitify?

Mac OS

**Comment by gal-legit** [comment]
The query result is actually valid as an organization member as well, so there's no reason to restrict it to organization owner only.
Resolving as not-a-bug.
