### ISSUE TITLE
legitify analyze --repo doesn't support gitlab projects within subgroups

### ISSUE THREAD

**Issue by mawl** [Legit-Labs/legitify#243]
### TL;DR

Hey,

We have projects in gitlab like group1/subgroup1/project1. The parameter --repo doesn't support them:

`Error: invalid repository format group1/subgroup1/project1 expected "owner/name".`

### Expected behavior

support them.

### Version

1.0.1

### On which operating system are you using legitify?

Linux

**Comment by noamd-legit** [comment]
Good catch. We will fix it.

**Comment by noamd-legit** [comment]
fixed

**Comment by mawl** [comment]
@noamd-legit: Thank you for fixing it. When will this be tagged? Because we use your binaries instead of compiling legitify on ourselves.

**Comment by royb-legit** [comment]
@mawl v1.0.2 was released today, containing this fix. Please let us know how it went.

**Comment by mawl** [comment]
@royb-legit: Thanks a lot! :)
