### ISSUE TITLE
"organization_has_too_many_admins" policy doesn't flag an organization with 8 owners

### ISSUE THREAD

**Issue by ajh-** [Legit-Labs/legitify#256]
### TL;DR

Currently have a GitHub Enterprise server with a dev organization that has 8 owners but legitify does not fail "organization_has_too_many_admins" policy

### Expected behavior

Expect "organization_has_too_many_admins" policy to fail with 4+ organization owners/admins configured

### Observed behavior

"organization_has_too_many_admins" policy passes even though there are 8 organizational owners/admins

### Version

v1.0.3

### On which operating system are you using legitify?

Linux

**Comment by noamd-legit** [comment]
Thanks for opening the issue @ajh- 
Please attach the error log from the execution.
and the output of this api request if possible:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/ORG/members?role=admin
```

**Comment by ajh-** [comment]
See attached. Just a note, the environment is a GitHub Enterprise instance.

[api_request_output.txt](https://github.com/Legit-Labs/legitify/files/13379287/api_request_output.txt)
[error.log](https://github.com/Legit-Labs/legitify/files/13379288/error.log)

**Comment by ajh-** [comment]
Hey @noamd-legit
Just tested the new release (v1.0.5) but I'm still getting the same results as before. Please let me know if you need any updated data.

**Comment by noamd-legit** [comment]
Reopening the issue
Do you mind reaching out by mail so I can further assist? legitify@legitsecurity.com

**Comment by JakubBiel** [comment]
This does not work for me either. I think the pagination is not working properly as the count of collaborators returns 30 even if that number is higher.
