### ISSUE TITLE
Add the needed permissions/scopes to the custom action documentation

### ISSUE THREAD

**Issue by rajbos** [Legit-Labs/legitify#259]
### TL;DR

The document does not state the necessary scopes for the authentication to GitHub, which leads to a permissions error on runtime (which also does not show the necessary scopes needed).

I would expect that info in the README [here](https://github.com/Legit-Labs/legitify/blob/45c571356d29d21d2ed3560e84d4a512c6cd1593/README.md?plain=1#L48).

### Expected behavior

Documentation indicates the scopes that are needed

### Version

main

### On which operating system are you using legitify?

Linux

### Relevant log output
Running on a single repo:
``` 
legitify failed with:
Using Github Cloud
Error: repository <org>/<repo> insufficient permissions
```

_No response_

**Comment by noamd-legit** [comment]
Hi @rajbos 

We mention in the readme the following scopes:

```
admin:org, read:enterprise, admin:org_hook, read:org, repo, read:repo_hook
```

Did you mean something else?

**Comment by noamd-legit** [comment]
Yeah you can use GITHUB_TOKEN for the action but only when running for the current repository otherwise it will fail. 
I'll clarify in the readme

Thank you!

**Comment by noamd-legit** [comment]
@rajbos I reverified the behavior, unfortunately currently GITHUB_TOKEN is not supported by the action since legitify requires access to `https://api.github.com/user/orgs` API 

I opened a feature request here: https://github.com/Legit-Labs/legitify/issues/265
