### ISSUE TITLE
1.0.5 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [Legit-Labs/legitify#269]
### Expected behavior

i can use 1.0.5 release

### Version

1.0.5

### On which operating system are you using legitify?

Linux

### Additional information

https://github.com/Homebrew/homebrew-core/pull/155167

**Comment by noamd-legit** [comment]
V1.0.5 shouldn't have been released yet.
Can we revert the formula to v1.0.4?
Otherwise, I can regenerate it but it won't be different from v1.0.4

Thank you @chenrui333! 🙏
