### ISSUE TITLE
"Reaching out" Message comes with every usage of legitify convert

### ISSUE THREAD

**Issue by mawl** [Legit-Labs/legitify#285]
### TL;DR

Just a small one :) - We are using `legitify convert `multiple times for different output formats in our ci job - and with every usage it shows:

`---> If you have any questions or you need assistance using legitify, please don't hesitate REACHING OUT @ legitify@legitsecurity.com`

### Expected behavior

Maybe you can show this message only on `legitify analyze`

### Version

1.0.7

### On which operating system are you using legitify?

Linux

**Comment by noamd-legit** [comment]
https://github.com/Legit-Labs/legitify/pull/288
