### ISSUE TITLE
Restricting email notifications (GitHub)

### ISSUE THREAD

**Issue by mackowski** [Legit-Labs/legitify#293]
### TL;DR

When user use one account for personal and work duties, some actions potentially leak information (for example in PR notification).
Using one account is recommended by GH https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#personal-accounts
Organisations can protect themselves by restricting email notifications https://docs.github.com/en/enterprise-server@3.8/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/restricting-email-notifications-for-your-organization#restricting-email-notifications

**Comment by Tal-Legit** [comment]
Hey :) Thank you for your suggestion. 
I added this policy on the enterprise level, as can be seen in this PR: https://github.com/Legit-Labs/legitify/pull/294 

Any input would be much appreciated before it is merged.
