### ISSUE TITLE
Skip evaluating archived GitHub repos in an org

### ISSUE THREAD

**Issue by abacchilb** [Legit-Labs/legitify#297]
### TL;DR

I would like to be able to set a flag to skip analyzing archived repos in my GitHub organization so I don't have to comb through results of repos that are out of scope. Maybe making that a default behavior would be welcome.

**Comment by noamd-legit** [comment]
Added support here: https://github.com/Legit-Labs/legitify/commit/c4118c9fe69c57474d08bc2b4396211d7b07e4bc
