### ISSUE TITLE
Fine-grained PAT not supported

### ISSUE THREAD

**Issue by edwardsph** [Legit-Labs/legitify#37]
### TL;DR

The README refers to GitHub's new fine-grained personal access tokens but if you use one you get an error:
```
Error: GitHub token seems invalid (should have 40 characters)
```

### Expected behavior

Accept fine grained access token

### Version

0.1.5

### On which operating system are you using legitify?

Linux

**Comment by gal-legit** [comment]
@edwardsph thank you for reporting this issue.
Fine-grained tokens shouldn't have been added to the readme.
Unfortunately, Github's fine-grained tokens do not support the GraphQL API currently.

@noamd-legit action items:
- Edit Readme to reflect the missing support and the reasoning.
- Add a special check for fine-grained tokens (length: 93, prefix: `github_pat_`) to alert users.
